version: '3'

services:

  hass_dev:
    # image: ghcr.io/home-assistant/home-assistant:2023.10.5
    image: ghcr.io/home-assistant/home-assistant:2024.1.5
    container_name: hass_dev
    # network_mode: host
    ports:
      - 8000:8123
    environment:
      - TZ=Europe/Paris
      - PYTHONUNBUFFERED=1
      - REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
    volumes:
      - ./config:/config
