name: "Publish"

on:
  release:
    types: [published]

jobs:
  publish:
    name: "Publish"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: "Update version"
        run: |
          yq -i -o json '.version="${{ github.event.release.tag_name }}"' "${{ github.workspace }}/custom_components/additional_ca/manifest.json"

      - name: "Zip component"
        run: |
          cd "${{ github.workspace }}/custom_components/additional_ca"
          zip "${{ github.workspace }}/additional_ca.zip" -r ./

      - name: "Upload assets"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ github.event.release.tag_name }} "${{ github.workspace }}/additional_ca.zip"
