name: "Publish"

on:
  release:
    types: [published]

defaults:
  run:
    working-directory: custom_components

jobs:
  publish:
    name: "Publish"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: "Update version"
        run: |
          current="$(jq --raw-output .version additional_ca/manifest.json | sed 's/\./\\./g')"
          sed -i s/$current/${{ github.event.release.tag_name }}/ additional_ca/manifest.json

      - name: "Zip component"
        run: |
          zip additional_ca.zip -r ./

      - name: "Upload assets"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ github.event.release.tag_name }} additional_ca.zip
